[general]
import = [
    "~/.config/alacritty/themes/themes/tokyo_night.toml"
]
live_config_reload = true

[window]
decorations = "Transparent"
opacity = 0.9
# blur = true
# padding = { x = 5, y = 25 }

[font]
normal = { family = "GohuFont uni14 Nerd Font Mono", style = "Regular" }
size = 13 

[colors.primary]
# background = "#1e2930"

[colors]
transparent_background_colors = true
