[general]
import = [
    "~/.config/alacritty/themes/themes/tokyo_night.toml"
]
live_config_reload = true

[window]
decorations = "Transparent"
opacity = 0.9
# blur = true
# padding = { x = 5, y = 25 }

[font]
normal = { family = "DepartureMono Nerd Font Mono", style = "Regular" }
size = 11 

[colors.primary]
background = "#000000"

[colors]
transparent_background_colors = true
