format = """
[ ▚ ▀ ▄▌▚](#425563)\
[ 󰄛 ](bg:#425563 fg:#80E0A7)\
[](bg:#80E0A7 fg:#425563)\
$directory\
[](fg:#80E0A7 bg:#7dd6e5)\
$git_branch\
$git_status\
[](fg:#7dd6e5 bg:#425563)\
$time\
[](fg:#425563)\
$fill\
$nodejs\
$rust\
$golang\
$php\
$python\
[▄▌▚](#425563)\
\n$character
"""
 
# Directory module
[directory]
style = "bold fg:#425563 bg:#80E0A7"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
 
# Git branch
[git_branch]
symbol = ""
style = "bg:#7dd6e5"
format = '[[ $symbol $branch ](fg:#000000 bg:#7dd6e5)]($style)'
 
# Git status
[git_status]
style = "bg:#7dd6e5"
format = '[[($all_status$ahead_behind )](fg:#000000 bg:#7dd6e5)]($style)'
 
# Time
[time]
disabled = false
time_format = "%R"
style = "bg:#1e1e2e"
format = '[[  $time ](fg:#80E0A7 bg:#425563)]($style)'
 
# Fill
[fill]
symbol = "─"
style = "fg:#425563"
 
# NodeJS
[nodejs]
symbol = ""
style = "bg:#425563"
format = '[[ $symbol ($version) ](bg:#425563 fg:#80E0A7)]($style)'
 
# Rust
[rust]
symbol = ""
style = "bg:#1e1e2e"
format = '[[ $symbol ($version) ](bg:#425563 fg:#80E0A7)]($style)'
 
# Go
[golang]
symbol = ""
style = "bg:#1e1e2e"
format = '[[ $symbol ($version) ](bg:#425563 fg:#80E0A7)]($style)'
 
# PHP
[php]
symbol = ""
style = "bg:#1e1e2e"
format = '[[ $symbol ($version) ](bg:#425563 fg:#80E0A7)]($style)'
 
# Python
[python]
symbol = ""
style = "fg:#8aadf4 bg:#1e1e2e"
format = '[[ $symbol (${version}) ](bg:#425563 fg:#80E0A7)]($style)'
